name: Build Android APK

on:
  push:
    branches: [ master ]
    paths:
      - 'android-kivy/**'
      - '.github/workflows/build-android-apk.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'android-kivy/**'
      - '.github/workflows/build-android-apk.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-android-apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            wget \
            unzip \
            openjdk-17-jdk \
            build-essential \
            libffi-dev \
            libssl-dev \
            python3-dev \
            python3-pip \
            python3-venv \
            zlib1g-dev \
            libjpeg-dev \
            libfreetype6-dev \
            liblcms2-dev \
            libwebp-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libxcb1-dev

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Configure Buildozer
        run: |
          cd android-kivy
          # Initialize buildozer if not already done
          if [ ! -f "buildozer.spec" ]; then
            buildozer init
          fi

      - name: Build APK
        run: |
          cd android-kivy
          # Build debug APK
          buildozer android debug
        env:
          # Set environment variables for build
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android-kivy/bin/*.apk
          retention-days: 30

      - name: Create Release (on master branch)
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: android-apk-${{ github.sha }}
          name: Android APK Build
          body: |
            Android APK build from commit ${{ github.sha }}
            
            **Download the APK file from the artifacts above.**
            
            ### Installation Instructions:
            1. Download the APK file
            2. Enable "Install from unknown sources" on your Android device
            3. Install the APK file
          files: android-kivy/bin/*.apk
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
